# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        exclude: src/gallery/*
  - repo: local
    hooks:
      - id: prettier
        name: Run Prettier
        entry: npm run prettier
        language: system
        types: [file]
        files: \.(js|jsx|ts|tsx|json|md|css|scss|html|astro)$
  - repo: local
    hooks:
      - id: eslint
        name: Run Linter
        entry: npm run lint
        language: system
        types: [file]
        files: \.(js|ts|astro)$
