name: Deploy Astro Site

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build the Astro site
        run: npm run build

      - name: Deploy to photography-portfolio repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
